In [ ]:
!pip install matplotlib-venn

Requirement already satisfied: matplotlib-venn in /usr/local/lib/python3.10/dist-packages (1.1.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from matplotlib-venn) (3.7.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from matplotlib-venn) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from matplotlib-venn) (1.13.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (4.54.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->matplotlib-venn) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->matplotlib-venn) (1.16.0)

In [ ]:
import pandas as pd
from matplotlib_venn import venn3, venn3_circles
import matplotlib.pyplot as plt

# leer las bases de datos de los resultados de cada modelo ML

In [ ]:
KNN_df = pd.read_csv('/content/drive/MyDrive/Doctorado/Set de Datos 2/Objetivo 4/2_KNN/Positivos_Sen_KNN.csv')

In [ ]:
SVM_df = pd.read_csv('/content/drive/MyDrive/Doctorado/Set de Datos 2/Objetivo 4/3_SVM/Positivos_Sen_SVM.csv')

In [ ]:
tree_df = pd.read_csv('/content/drive/MyDrive/Doctorado/Set de Datos 2/Objetivo 4/1_RF/Positivos_Sen_ctd_random_forest.csv')

In [ ]:
tree_df

,GeneSymbol,SMILES,ChemicalName,Interaction,InteractionActions,Total Molweight,Molweight,Monoisotopic Mass,cLogP,cLogS,...,Non-Aromatic Hetero-Rings,Hetero-Aromatic Rings,Amides,Amines,Alkyl-Amines,Aromatic Amines,Aromatic Nitrogens,Basic Nitrogens,Acidic Oxygens,Prediccion
0,AKT1,[B-]12(OC3C(C(OC3(O1)CO)CO)O)OC4C(C(OC4(O2)CO)...,calcium fructoborate,calcium fructoborate affects the expression of...,affects^expression,774.258,367.0900,367.104785,-5.2466,2.630,...,4,0,0,0,0,0,0,0,0,1
1,PTEN,[B-]12(OC3C(C(OC3(O1)CO)CO)O)OC4C(C(OC4(O2)CO)...,calcium fructoborate,calcium fructoborate results in increased expr...,increases^expression,774.258,367.0900,367.104785,-5.2466,2.630,...,4,0,0,0,0,0,0,0,0,1
2,EIF4EBP1,[B-]12(OC3C(C(OC3(O1)CO)CO)O)OC4C(C(OC4(O2)CO)...,calcium fructoborate,calcium fructoborate affects the expression of...,affects^expression,774.258,367.0900,367.104785,-5.2466,2.630,...,4,0,0,0,0,0,0,0,0,1
3,TSC2,[B-]12(OC3C(C(OC3(O1)CO)CO)O)OC4C(C(OC4(O2)CO)...,calcium fructoborate,calcium fructoborate results in increased expr...,increases^expression,774.258,367.0900,367.104785,-5.2466,2.630,...,4,0,0,0,0,0,0,0,0,1
4,TP53,[Be+2].[O-]S(=O)(=O)[O-],beryllium sulfate,beryllium sulfate promotes the reaction [TP53 ...,affects^binding|increases^reaction,105.074,98.0779,97.967380,-3.4103,1.524,...,0,0,0,0,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25735,STAT3,OO.OO.OO.[O-][V](=O)([O-])[O-].[Na+].[Na+].[Na+],pervanadate,pervanadate inhibits the reaction [Capsaicin r...,decreases^activity|decreases^phosphorylation|d...,285.950,117.9620,117.947097,0.3317,3.280,...,0,0,0,0,0,0,0,0,0,1
25736,STAT3,OO.OO.OO.[O-][V](=O)([O-])[O-].[Na+].[Na+].[Na+],pervanadate,pervanadate inhibits the reaction [Emodin resu...,decreases^activity|decreases^phosphorylation|d...,285.950,117.9620,117.947097,0.3317,3.280,...,0,0,0,0,0,0,0,0,0,1
25737,STAT3,OO.OO.OO.[O-][V](=O)([O-])[O-].[Na+].[Na+].[Na+],pervanadate,pervanadate inhibits the reaction [geranylnari...,decreases^phosphorylation|decreases^reaction,285.950,117.9620,117.947097,0.3317,3.280,...,0,0,0,0,0,0,0,0,0,1
25738,STAT3,OO.OO.OO.[O-][V](=O)([O-])[O-].[Na+].[Na+].[Na+],pervanadate,pervanadate inhibits the reaction [tubocapseno...,decreases^phosphorylation|decreases^reaction,285.950,117.9620,117.947097,0.3317,3.280,...,0,0,0,0,0,0,0,0,0,1
25739,RELA,OO.OO.OO.[O-][V](=O)([O-])[O-].[Na+].[Na+].[Na+],pervanadate,Fenretinide inhibits the reaction [pervanadate...,decreases^reaction|increases^activity,285.950,117.9620,117.947097,0.3317,3.280,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
print(KNN_df.columns)
print(SVM_df.columns)
print(tree_df.columns)

Index(['GeneSymbol', 'SMILES', 'ChemicalName', 'Interaction',
       'InteractionActions', 'Total Molweight', 'Molweight',
       'Monoisotopic Mass', 'cLogP', 'cLogS', 'H-Acceptors', 'H-Donors',
       'Total Surface Area', 'Relative PSA', 'Polar Surface Area',
       'Druglikeness', 'Mutagenic', 'Tumorigenic', 'Reproductive Effective',
       'Irritant', 'Shape Index', 'Molecular Flexibility',
       'Molecular Complexity', 'Fragments', 'Non-H Atoms', 'Non-C/H Atoms',
       'Metal-Atoms', 'Electronegative Atoms', 'Stereo Centers',
       'Rotatable Bonds', 'Rings Closures', 'Aromatic Atoms', 'sp3-Atoms',
       'Small Rings', 'Carbo-Rings', 'Hetero-Rings', 'Saturated Rings',
       'Non-Aromatic Rings', 'Aromatic Rings', 'Saturated Carbo-Rings',
       'Non-Aromatic Carbo-Rings', 'Carbo-Aromatic Rings',
       'Saturated Hetero-Rings', 'Non-Aromatic Hetero-Rings',
       'Hetero-Aromatic Rings', 'Amides', 'Amines', 'Alkyl-Amines',
       'Aromatic Amines', 'Aromatic Nitrogens', 'Basic Nitrogens',
       'Acidic Oxygens', 'Predicciones', 'Probabilidad'],
      dtype='object')
Index(['GeneSymbol', 'SMILES', 'ChemicalName', 'Interaction',
       'InteractionActions', 'Total Molweight', 'Molweight',
       'Monoisotopic Mass', 'cLogP', 'cLogS', 'H-Acceptors', 'H-Donors',
       'Total Surface Area', 'Relative PSA', 'Polar Surface Area',
       'Druglikeness', 'Mutagenic', 'Tumorigenic', 'Reproductive Effective',
       'Irritant', 'Shape Index', 'Molecular Flexibility',
       'Molecular Complexity', 'Fragments', 'Non-H Atoms', 'Non-C/H Atoms',
       'Metal-Atoms', 'Electronegative Atoms', 'Stereo Centers',
       'Rotatable Bonds', 'Rings Closures', 'Aromatic Atoms', 'sp3-Atoms',
       'Small Rings', 'Carbo-Rings', 'Hetero-Rings', 'Saturated Rings',
       'Non-Aromatic Rings', 'Aromatic Rings', 'Saturated Carbo-Rings',
       'Non-Aromatic Carbo-Rings', 'Carbo-Aromatic Rings',
       'Saturated Hetero-Rings', 'Non-Aromatic Hetero-Rings',
       'Hetero-Aromatic Rings', 'Amides', 'Amines', 'Alkyl-Amines',
       'Aromatic Amines', 'Aromatic Nitrogens', 'Basic Nitrogens',
       'Acidic Oxygens', 'Prediction'],
      dtype='object')
Index(['GeneSymbol', 'SMILES', 'ChemicalName', 'Interaction',
       'InteractionActions', 'Total Molweight', 'Molweight',
       'Monoisotopic Mass', 'cLogP', 'cLogS', 'H-Acceptors', 'H-Donors',
       'Total Surface Area', 'Relative PSA', 'Polar Surface Area',
       'Druglikeness', 'Mutagenic', 'Tumorigenic', 'Reproductive Effective',
       'Irritant', 'Shape Index', 'Molecular Flexibility',
       'Molecular Complexity', 'Fragments', 'Non-H Atoms', 'Non-C/H Atoms',
       'Metal-Atoms', 'Electronegative Atoms', 'Stereo Centers',
       'Rotatable Bonds', 'Rings Closures', 'Aromatic Atoms', 'sp3-Atoms',
       'Small Rings', 'Carbo-Rings', 'Hetero-Rings', 'Saturated Rings',
       'Non-Aromatic Rings', 'Aromatic Rings', 'Saturated Carbo-Rings',
       'Non-Aromatic Carbo-Rings', 'Carbo-Aromatic Rings',
       'Saturated Hetero-Rings', 'Non-Aromatic Hetero-Rings',
       'Hetero-Aromatic Rings', 'Amides', 'Amines', 'Alkyl-Amines',
       'Aromatic Amines', 'Aromatic Nitrogens', 'Basic Nitrogens',
       'Acidic Oxygens', 'Prediccion'],
      dtype='object')

In [ ]:

# Agregar columna "modelo" a cada dataframe
#KNN_df['modelo'] = 'KNN'
#SVM_df['modelo'] = 'SVM'
#tree_df['modelo'] = 'DTC'

In [ ]:
# Seleccionar columnas
#KNN_df = KNN_df[['ChemicalName', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Predicciones', 'modelo']]
#SVM_df = SVM_df[['ChemicalName', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Prediction', 'modelo']]
#tree_df = tree_df[['ChemicalName', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds','Prediccion', 'modelo']]

# Cambiar nombre a columnas
#KNN_df.columns = ['Name', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Senotherapeutics:', 'Modelo']
#SVM_df.columns = ['Name', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Senotherapeutics:', 'Modelo']
#tree_df.columns = ['Name', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Senotherapeutics:', 'Modelo']

In [ ]:
# Seleccionar columnas
KNN_df = KNN_df[['ChemicalName', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Predicciones']]
SVM_df = SVM_df[['ChemicalName', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Prediction']]
tree_df = tree_df[['ChemicalName', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds','Prediccion']]

# Cambiar nombre a columnas
KNN_df.columns = ['Name', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Senotherapeutics:']
SVM_df.columns = ['Name', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Senotherapeutics:']
tree_df.columns = ['Name', 'SMILES', 'Total Molweight', 'cLogP', 'H-Acceptors', 'H-Donors', 'Total Surface Area', 'Relative PSA', 'Rotatable Bonds', 'Senotherapeutics:']

In [ ]:
# positivos indicados en Senotherapeutics para cada dataframe

# Obtener los positivos para cada modelo
KNN_positivos = KNN_df[KNN_df['Senotherapeutics:'] == 1]['Name'].tolist()
SVM_positivos = SVM_df[SVM_df['Senotherapeutics:'] == 1]['Name'].tolist()
tree_positivos = tree_df[tree_df['Senotherapeutics:'] == 1]['Name'].tolist()

print("KNN Positivos:", len(KNN_positivos))
print("SVM Positivos:", len(SVM_positivos))
print("Árbol Positivos:", len(tree_positivos))

KNN Positivos: 14571
SVM Positivos: 21346
Árbol Positivos: 25740

In [ ]:
# prompt: encuentra las filas que sean iguales en los tres dataframe

# Encontrar la intersección de los tres conjuntos de positivos
common_positives = set(KNN_positivos) & set(SVM_positivos) & set(tree_positivos)

print("Compuestos comunes en los tres modelos:", len(common_positives))

# Mostrar los nombres de los compuestos comunes
print(list(common_positives))


# Crear un nuevo dataframe con los compuestos comunes
common_df = pd.concat([
    KNN_df[KNN_df['Name'].isin(common_positives)],
    SVM_df[SVM_df['Name'].isin(common_positives)],
    tree_df[tree_df['Name'].isin(common_positives)]
])

Compuestos comunes en los tres modelos: 714
['3-((3-trifluoromethyl)phenyl)-5-((3-carboxyphenyl)methylene)-2-thioxo-4-thiazolidinone', 'Genistein', '(19Z)-halichondramide', 'GLX351322', 'bisindolylmaleimide IX', 'Teniposide', "pyridoxal phosphate-6-azophenyl-2',4'-disulfonic acid", 'AICA ribonucleotide', 'kurarinol', 'L 685458', 'BX795', 'Everolimus', 'selinexor', 'ginsenoside Rh1', 'acalabrutinib', 'procyanidin', 'agrimoniin', 'isosalipurposide', 'ridaforolimus', '4-((alpha-L-rhamnosyloxy)benzyl)isothiocyanate', 'Aminopterin', '6-(4-chlorophenyl)imidazo(2,1-b)(1,3)thiazole-5-carbaldehyde O-(3,4-dichlorobenzyl)oxime', 'Bleomycin', 'Thiostrepton', 'manumycin', 'darbufelone', 'mocetinostat', 'salvianolic acid', 'Zeocin', 'Iopamidol', 'beclomethasone 17-monopropionate', 'ginsenoside Rh2', 'syringin', 'z-Val-Ala-Asp(Ome)-fluoromethylketone', 'alisol B', 'LY-2157299', 'alisol B 23-acetate', 'VS-5584', 'herbimycin', 'rottlerin', 'pimobendan', 'ziyuglycoside I', 'Erythromycin', 'Uridine Triphosphate', '1,2-linoleoylphosphatidylcholine', 'olaparib', 'cucurbitacin E', 'swietenine', 'Thapsigargin', 'Floxacillin', 'procyanidin B2', 'AM 251', '2-(4-nitrophenyl)-4-(4-fluorophenyl)-5-(4-pyridinyl)-1H-imidazole', '7,8-diacetoxy-4-methylthiocoumarin', '9-methoxycamptothecin', 'bafilomycin A', "theaflavin-3,3'-digallate", 'isoangustone A', 'tapotoclax', 'gossypetin', '1,3-dihydro-1-(1-((4-(6-phenyl-1H-imidazo(4,5-g)quinoxalin-7-yl)phenyl)methyl)-4-piperidinyl)-2H-benzimidazol-2-one', 'INCB057643', 'nutlin 3', 'Mitomycin', 'saikosaponin D', 'ARV-825', 'troxerutin', 'lipoteichoic acid', 'Crizotinib', 'Filipin', 'monascin', 'neratinib', 'CGK 733', "5'-methylthioadenosine", 'bafilomycin A1', 'acyline', 'cerivastatin', 'pirarubicin', 'Prodigiosin', 'lupalbigenin', 'Colchicine', 'isosilybin A', 'morroniside', 'alpha-solanine', 'eriodictyol', 'Bosentan', 'AS602868', 'SD-208', '2-((3-acrylamido-4-methylphenyl)amino)-N-(2-methyl-5-(3,4,5-trimethoxybenzamido)phenyl)-4-(methylamino)pyrimidine-5-carboxamide', 'zafirlukast', 'indirubin', 'Amphotericin B', 'Nicardipine', 'carfilzomib', 'Saquinavir', 'Tetradecanoylphorbol Acetate', 'picrasidine I', 'ajugasterone C', 'Clarithromycin', 'abexinostat', '4-(4-fluorophenyl)-2-(4-hydroxyphenyl)-5-(4-pyridyl)imidazole', 'N-acetylglucosaminono-1,5-lactone O-(phenylcarbamoyl)oxime', 'retrorsine', '5-chloro-N2-(1-(5-fluoropyridin-2-yl)ethyl)-N4-(5-isopropoxy-1H-pyrazol-3-yl)pyrimidine-2,4-diamine', 'glycitin', 'pomiferin', 'Trabectedin', 'NVP-BHG712', 'plastochromanol 8', 'ETP-45299', 'dinophysistoxin 2', 'Akt-I-1,2 compound', 'temsirolimus', 'Methylprednisolone', 'rosavin', 'crocin', 'cyclo(Trp-Asp-Pro-Val-Leu)', 'gastrin 17', 'calix(6)arene', 'gedunin', '2-(1-(3-dimethylaminopropyl)-5-methoxyindol-3-yl)-3-(1H-indol-3-yl)maleimide', 'Bortezomib', 'paxilline', 'senkirkine', 'salvianolic acid A', 'Proanthocyanidins', 'Meloxicam', 'DIBA-1', 'Vemurafenib', 'phorbol-12-myristate', 'gallocatechol', "N'-(3-bromo-4-hydroxybenzylidene)-2-(9-oxo-10(9H)-acridinyl)acetohydrazide", 'ginsenoside Rg3', 'Omeprazole', 'RG7112', '10-hydroxycamptothecin', 'amyloid beta-protein (1-40)', 'tolmetin glucuronide', 'avermectin', 'vernodalin', 'alvocidib', 'ralimetinib', 'kolaviron', 'notoginsenoside R1', 'CA 074 methyl ester', 'tofacitinib', 'mithramycin A', 'anemoside A3', "2-(4-(2-carboxyethyl)phenethylamino)-5'-N-ethylcarboxamidoadenosine", 'Leucovorin', 'daidzin', 'chymostatin', 'NSC-87877', 'Cephalothin', 'beta-Endorphin', '103D5R', 'Leuprolide', 'arzanol', 'Troglitazone', 'tephrosin', 'PX-866', 'salinomycin', 'bryostatin 1', "4,4'-Diisothiocyanostilbene-2,2'-Disulfonic Acid", 'otosenine', 'epicatechin gallate', 'bleomycetin', 'Uridine Diphosphate', 'Nocodazole', 'Monocrotaline', 'semaglutide', 'Vincristine', 'ABT-737', 'Demeclocycline', 'gamabufotalin', 'CEP-11004', 'baohuoside I', 'Dactinomycin', 'icariin', '5-amino-7-(cyclohexylamino)-1-ethyl-6-fluoro-4-oxo-1,4-dihydroquinoline-3-carboxylic acid', 'ioversol', 'formosanin C', 'Triamterene', 'cucurbitacin B', 'CPI203', 'aspalathin', 'jacobine', 'CPI-0610', 'KCC 009', '(5-(2,4-bis((3S)-3-methylmorpholin-4-yl)pyrido(2,3-d)pyrimidin-7-yl)-2-methoxyphenyl)methanol', 'OTX015', 'sanggenone C', 'geldanamycin', 'quercitrin', 'aflatoxin G1', 'spiraeoside', 'idelalisib', 'Paromomycin', 'procyanidin B1', 'crenigacestat', 'aucubin', 'N-(4-(N-(3-methoxypyrazin-2-yl)sulfamoyl)phenyl)-3-(5-nitrothiophene-2-yl)acrylamide', 'hypsiziprenol A9', 'GSK1210151A', 'hemistepsin', 'coagulin-L', 'madecassoside', 'ginsenoside Rb1', 'prexasertib', 'Meropenem', 'withaferin A', 'microcystin RR', 'gedatolisib', 'N-Formylmethionine Leucyl-Phenylalanine', 'Phenolsulfonphthalein', 'kaempferol', 'Nystatin', 'iomeprol', 'tubeimoside II', 'TAK-165', 'JNK-IN-8', '7,8-diacetoxy-4-methylcoumarin', 'Neurotensin', 'Catechin', 'Silymarin', 'U 0126', 'epigallocatechin gallate', 'JBIR-99', 'ICG 001', 'raltitrexed', '(E)-4-((2-N-(4-methoxybenzenesulfonyl)amino)stilbazole)1-oxide', 'amentoflavone', 'Alpha-Amanitin', 'eupafolin', 'azaribine', 'Vinblastine', 'PQQ Cofactor', 'primycin', 'lariciresinol', 'calycosin-7-O-beta-D-glucoside', 'phenylalanyl-cyclo(cysteinyltyrosyl-tryptophyl-ornithyl-threonyl-penicillamine)threoninamide', 'INCB054329', 'puerarin', 'Cyclosporine', 'apicidin', 'leupeptin', '5,7-dihydroxy-3-(3-hydroxy-4-methoxybenzyl)-6-methoxychroman-4-one', 'nitazoxanide', 'Pravastatin', 'annonacin', 'imetelstat', 'Antimycin A', 'Geraniin', 'Tetrodotoxin', 'NE-52-qq57', '3-deazaneplanocin', 'salubrinal', 'midecamycin', 'Hesperidin', 'pentagalloylglucose', 'Silybin', 'sanglifehrin A', 'Biliverdine', 'talazoparib', "2',4'-dichlorobenzamil amiloride", 'scolymoside', 'bruceantinol', 'destruxin B', 'astragaloside VI', 'tubocapsenolide A', 'Olanzapine', 'N-(cyanomethyl)-4-(2-((4-(4-morpholinyl)phenyl)amino)-4-pyrimidinyl)benzamide', 'andrographolide', 'chebulic acid', 'NSC668394', 'medermycin', 'didymin', 'ibrutinib', 'digalloylresveratrol', 'benzyloxycarbonylvalyl-alanyl-aspartyl fluoromethyl ketone', 'acetylspiramycin', 'resiniferatoxin', 'StemRegenin 1', "4'-O-methylalpinumisoflavone", 'geniposide', 'araloside A', 'ginsenoside Rg1', 'warangalone', 'gardenia yellow', 'auriculasin', 'glimepiride', 'palytoxin', 'ginsenoside Re', 'mivebresib', 'columbamine', 'sulindac sulfone', 'Camptothecin', 'Nelfinavir', '7-monohydroxyethylrutoside', 'isoquercitrin', 'Heme', 'Rotenone', 'methyl protodioscin', 'N-(4-((3-(2-amino-4-pyrimidinyl)-2-pyridinyl)oxy)phenyl)-4-(4-methyl-2-thienyl)-1-phthalazinamine', 'resiquimod', 'Wortmannin', 'brassinolide', 'diphlorethohydroxycarmalol', 'GSK690693', 'gossypin', 'Ionomycin', 'chikusetsusaponin V', 'ircinin-1', 'kaempferol 7-O-glucoside', 'Dexamethasone', 'SP2509', 'nilotinib', 'brazilein', 'Minocycline', 'bisindolylmaleimide', '5,7-dihydroxy-6-methoxy-2-phenylchromen-4-one', 'lixisenatide', 'Axitinib', 'IC 87114', "3',4',7-trihydroxyisoflavone", 'yessotoxin', 'acteoside', 'calcein AM', 'Monensin', '2-phenyl-4-(3-pyridin-2-yl-1H-pyrazol-4-yl)pyridine', 'A-1210477', 'astragaloside A', 'GSK0660', 'azadirachtin', 'JTE 013', 'triphlorethol-A', 'skullcapflavone II', 'adavosertib', 'leptocarpin', 'Vitamin B 12', '7-methylguanosine triphosphate', 'ravoxertinib', 'eurycomanone', 'chlamydocin', 'AZ-628', 'enzalutamide', 'protoporphyrin IX', 'Dipyridamole', 'Sirolimus', 'cudraflavone B', 'seneciphylline', 'Calcimycin', 'tyrphostin AG825', 'Miransertib', 'copanlisib', 'SB 203580', 'Simvastatin', 'ginsenoside Rk1', 'nimbolide', 'Colistin', '4-(5-benzo(1,3)dioxol-5-yl-4-pyridin-2-yl-1H-imidazol-2-yl)benzamide', 'icatibant', 'AP20187', 'tanespimycin', '3-O-caffeoyl-1-methylquinic acid', 'osajin', 'Melitten', 'evernic acid', 'Cytochalasin B', 'timosaponin AIII', 'maxacalcitol', '(4-(((2-(3-fluoro-4-(trifluoromethyl)phenyl)-4-methyl-1,3-thiazol-5-yl)methyl)sulfanyl)-2-methylphenoxy)acetic acid', 'gyrophoric acid', 'diacetyldiphenylurea bisguanylhydrazone', 'CU-CPT22', 'casticin', 'beta-Glucans', 'Trp-Lys-Tyr-Met-Val-Met', 'toosendanin', 'cyanoginosin LR', 'FR 180204', 'luteolin-7-glucoside', 'licoricidin', 'Rutin', 'lornoxicam', 'senecionine', 'Indirubin E804', 'Paclitaxel', 'monorden', '2,3,5-(triglutathion-S-yl)hydroquinone', 'Ecdysterone', 'YM-254890', 'deacylcortivazol', 'GSK343', 'Azithromycin', 'anemoside B4', 'nemorubicin', 'PKI 166', 'labedipinedilol A', 'epoxomicin', 'sapanisertib', 'Cefazolin', 'moringin', '11-nor-delta(9)-tetrahydrocannabinol-9-carboxylic acid', 'phorbol-12,13-didecanoate', 'BI-2852', 'piperlongumine', 'mangostin', 'Amlodipine', 'Tubocurarine', 'EPZ004777', 'MK 2206', 'astaxanthine', 'gambogic acid', 'platycodin D', 'archazolid B', 'hellebrigenin', 'capsazepine', 'Guanosine Triphosphate', 'Cefotaxime', 'dihydromyricetin', 'cabazitaxel', 'aurofusarin', 'Digitoxin', 'N-(4-(2-ethyl-4-(3-methylphenyl)-1,3-thiazol-5-yl)-2-pyridyl)benzamide', 'calyculin A', 'Epirubicin', 'venetoclax', 'ON123300', 'cucurbitacin IIa', 'GDP 366', 'GW8510', 'olomoucine II', 'catalpol', 'Vinorelbine', 'Ku 0063794', 'hyperoside', 'cotylenin A', 'NSC 74859', 'LY 117018', 'apigenin-6,8-di-C-glycopyranoside', 'lactacystin', 'iodixanol', 'SRT2183', "N-((2-(hydroxyaminocarbonyl)methyl)-4-methylpentanoyl)-3-(2'-naphthyl)alanylalanine, 2-aminoethylamide", 'saponin QA-21V1', 'Rifampin', 'Phosphatidylcholines', 'dieckol', 'rubitecan', 'ginsenoside M1', 'jaceosidin', 'Coumestrol', 'Aflatoxin M1', 'tipifarnib', 'S63845', 'cyclosporin H', 'nodularin', 'Lopinavir', 'Ouabain', 'quizartinib', 'SCH772984', "3-(5'-hydroxymethyl-2'-furyl)-1-benzylindazole", 'dulaglutide', 'echimidine', 'CRT 0066101', 'delta(9)-tetrahydrocannabinolic acid', 'enzastaurin', 'satratoxin G', 'zomepirac glucuronide', 'LGK974', 'oenothein B', 'epsilon-viniferin', 'quercetin 3-O-glucuronide', 'Cefadroxil', '1,2-distearoyllecithin', 'fumonisin B1', 'Daunorubicin', 'Cytochalasin D', 'FSL-1 lipoprotein, synthetic', 'Novobiocin', 'riddelliine', 'siomycin A', 'triciribine', 'azaspiracid', 'surfactin peptide', 'paederosidic acid', 'JTE 907', 'phosphoramidon', 'Methotrexate', 'Riboflavin', 'asiatic acid', 'ON 01910', 'Nimodipine', 'hydroxysafflor yellow A', 'mulberroside A', 'sotrastaurin', 'Ritonavir', 'bathocuproine sulfonate', 'Plicamycin', 'scutebarbatine A', 'vistusertib', 'rebamipide', 'zinc protoporphyrin', 'alisol A 24-acetate', 'epimedokoreanin B', 'navitoclax', 'voacamine', 'Josamycin', 'bergenin', 'Roxithromycin', 'kukoamine B', 'iberiotoxin', 'lasiocarpine', 'Gossypol', 'NSC 689534', 'pepstatin', 'bisoxatin acetate', 'Docetaxel', 'naringin', 'Liraglutide', 'lercanidipine', 'PF 3758309', 'Insulin', 'casuarictin', 'tetra(4-N-methylpyridyl)porphine', 'ziyuglycoside II', 'OSI 027', 'atranorin', 'BMS 536924', 'aspidin BB', 'nothofagin', '4-(4-(3-(pyridin-2-yl)-1H-pyrazol-4-yl)pyridin-2-yl)-N-(tetrahydro-2H-pyran-4-yl)benzamide', 'ZD 9331', 'cucurbitacin I', 'pazopanib', 'Tacrolimus', 'Mycophenolic Acid', 'plantamajoside', 'GSK-2816126', 'Topotecan', 'bisindolylmaleimide I', 'Ubiquinone', 'Amygdalin', 'sparstolonin B', 'Folic Acid', 'AZD 1480', '10-decarbamoylmitomycin C', 'Phosphatidylinositol 4,5-Diphosphate', "2''-galloylhyperin", 'trichodesmine', 'Prednisolone', 'bicalutamide', 'olmesartan', '5,7-dihydroxy-2-methyl-8-(4-(3-hydroxy-1-methyl)-piperidinyl)-4H-1-benzopyran-4-one', 'Doxycycline', 'ptaquiloside', 'cyanidin-3-O-beta-glucopyranoside', 'Suramin', 'sitaxsentan', 'lly-283', 'ruxolitinib', 'STF-118804', '14-deoxy-11,12-didehydroandrographolide', 'forsythoside B', 'remdesivir', 'nifuroxazide', 'PIK 75', 'plitidepsin', 'Irinotecan', 'CX 5461', 'PD 173074', 'dactolisib', 'brevetoxin 2', 'Colforsin', 'NADP', 'Tigecycline', 'panduratin A', 'Doxorubicin', 'asparanin A', "3'-O-(4-benzoyl)benzoyladenosine 5'-triphosphate", 'Rosmarinic Acid', 'Ro 31-8220', 'PP242', '3-Pyridinecarboxylic acid, 1,4-dihydro-2,6-dimethyl-5-nitro-4-(2-(trifluoromethyl)phenyl)-, Methyl ester', 'Bilirubin', 'KN 62', 'alternariol', 'FR 173657', 'salvianolic acid B', 'Sulfasalazine', 'Ivermectin', 'BMS 754807', '5-((5-fluoro-2-oxo-1,2-dihydro-3H-indol-3-ylidene)methyl)-N-(2-hydroxy-3-morpholin-4-ylpropyl)-2,4-dimethyl-1H-pyrrole-3-carboxamide', 'Vx-11e', 'PF 00477736', 'Goserelin', 'GSK2141795', 'epothilone A', 'ginsenoside F1', 'valspodar', 'VER 155008', 'Octreotide', 'Glycyrrhizic Acid', 'myricetin', 'entinostat', 'SM 164', 'Pemetrexed', 'dabrafenib', 'genistin', 'cruentaren A', 'Lapatinib', 'obacunone', 'neo-gambogic acid', 'pycnidione', 'Glyburide', 'trachelogenin', 'astilbin', "2'-epi-2'-O-acetylthevetin B", 'excavatolide B', 'ZK159222', 'Nitrovin', 'LR-90', 'iopromide', 'homocastasterone', 'Beclomethasone', 'N-(3-chloro-7-indolyl)-1,4-benzenedisulphonamide', 'Cloxacillin', 'Eptifibatide', 'tetracycline CMT-3', 'Fluorescein-5-isothiocyanate', 'praeruptorin A', 'ABBV-744', 'Luteolin', 'vaticanol C', 'Betalains', 'Chondroitin Sulfates', 'beauvericin', 'protoporphyrinogen', 'poncirin', 'eriocitrin', 'corilagin', 'baicalin', 'benzyloxycarbonyl-isoleucyl-glutamyl(O-tert-butyl)-alanyl-leucinal', 'Ellagic Acid', 'Chitosan', "5,7,3'-trihydroxy-3,4'-dimethoxyflavone", 'betadex', 'omipalisib', 'zopolrestat', 'Angiotensin II', 'fisetin', 'Chir 99021', 'batimastat', 'fucoxanthin', 'SF 2446A1', 'cirsimarin', 'Rimonabant', 'GW 506033X', 'cobaltiprotoporphyrin', 'PI103', 'Reserpine', 'N-(4-(2-amino-3-chloropyridin-4-yloxy)-3-fluorophenyl)-4-ethoxy-1-(4-fluorophenyl)-2-oxo-1,2-dihydropyridine-3-carboxamide', 'Guanosine Diphosphate', 'Dicumarol', '3,4-di-O-caffeoylquinic acid', 'HTS 466284', 'pomalidomide', 'FR900359', 'Dasatinib', 'alisol B monoacetate', 'cinobufotalin', 'dinophysistoxin 1', 'Iohexol', 'AZD5991', 'Lovastatin', 'sotorasib', 'GW 501516', 'dioscin', 'isovitexin', '17-(dimethylaminoethylamino)-17-demethoxygeldanamycin', 'ST 1481', 'cetrorelix', 'NAD', 'iron protoporphyrin IX', 'palbociclib', 'wogonoside', 'Oligonucleotides', 'homoorientin', 'oleuropein', 'STA 9090', 'romidepsin', 'mangiferin', 'afuresertib', 'Oligomycins', 'Tetracycline', 'XMU-MP-1', 'Okadaic Acid', 'Glutathione Disulfide', 'Indinavir', 'cisatracurium', 'morusin', 'lysocellin', 'Sucrose', 'glycitein', 'ST2825', 'withanone', 'GSK923295', 'Ceruletide', 'ophiopogonin D', 'lobetyolin', 'SNX 2112', 'myricitrin', 'capivasertib']

In [ ]:
# Mostrar las filas que son iguales en los tres dataframes
common_df.sort_values('Name').drop_duplicates(subset='Name')

,Name,SMILES,Total Molweight,cLogP,H-Acceptors,H-Donors,Total Surface Area,Relative PSA,Rotatable Bonds,Senotherapeutics:
9862,(19Z)-halichondramide,CC1CCC=CC2=NC(=CO2)C3=NC(=CO3)C4=NC(=CO4)C(C(C...,836.976,5.0626,16,1,674.23,0.27298,14,1
12305,(4-(((2-(3-fluoro-4-(trifluoromethyl)phenyl)-4...,CC1=C(C=CC(=C1)SCC2=C(N=C(S2)C3=CC(=C(C=C3)C(F...,471.494,5.1092,4,1,326.92,0.25988,8,1
17341,"(5-(2,4-bis((3S)-3-methylmorpholin-4-yl)pyrido...",CC1COCCN1C2=NC(=NC3=C2C=CC(=N3)C4=CC(=C(C=C4)O...,465.552,2.4865,9,1,351.95,0.23614,5,1
24343,(E)-4-((2-N-(4-methoxybenzenesulfonyl)amino)st...,COC1=CC=C(C=C1)S(=O)(=O)N=C2C=CC=CC2=CC=C3C=CN...,382.439,1.7590,6,1,292.14,0.22845,3,1
18070,"1,2-distearoyllecithin",CCCCCCCCCCCCCCCCCC(=O)OCC(COP(=O)([O-])OCC[N+]...,790.156,7.7767,9,0,695.34,0.12909,44,1
...,...,...,...,...,...,...,...,...,...,...
6764,zinc protoporphyrin,CC1=C(C2=CC3=NC(=CC4=C(C(=C([N-]4)C=C5C(=C(C(=...,626.042,5.1545,8,4,435.19,0.23151,8,1
14945,ziyuglycoside I,CC1CCC2(CCC3(C(=CCC4C3(CCC5C4(CCC(C5(C)C)OC6C(...,766.962,2.1065,13,8,526.90,0.29956,6,1
16873,ziyuglycoside II,CC1CCC2(CCC3(C(=CCC4C3(CCC5C4(CCC(C5(C)C)OC6C(...,604.822,3.9436,8,5,425.09,0.23181,3,1
12940,zomepirac glucuronide,CC1=C(N(C(=C1)CC(=O)OC2C(C(C(C(O2)C(=O)O)O)O)O...,467.857,-0.0007,10,4,323.57,0.36589,7,1
4479,zopolrestat,C1=CC=C2C(=C1)C(=NN(C2=O)CC3=NC4=C(S3)C=CC(=C4...,419.382,2.9351,6,1,280.92,0.30461,5,1

In [ ]:
# prompt: guardar en csv common_df

# ... (Your existing code) ...


# Mostrar las filas que son iguales en los tres dataframes
common_df = common_df.sort_values('Name').drop_duplicates(subset='Name')

# Guardar el dataframe en un archivo CSV en Google Drive
common_df.to_csv('/content/drive/MyDrive/Doctorado/Set de Datos 2/Objetivo 4/Compuestos_Comunes_modelos.csv', index=False)

In [ ]:
# cuantos datos positivos (1) compartes los modelos SVM y tree

# Encontrar la intersección entre SVM y Árbol de decisión
intersection_svm_tree = list(set(SVM_positivos) & set(tree_positivos))

print("Datos positivos compartidos entre SVM y Árbol de decisión:", len(intersection_svm_tree))

Datos positivos compartidos entre SVM y Árbol de decisión: 966

In [ ]:
# cuantos datos positivos (1) compartes los modelos SVM y KNN

# Encontrar la intersección entre SVM y KNN
intersection_svm_knn = list(set(SVM_positivos) & set(KNN_positivos))

print("Datos positivos compartidos entre SVM y KNN:", len(intersection_svm_knn))

Datos positivos compartidos entre SVM y KNN: 770

In [ ]:
#  cuantos datos positivos (1) compartes los modelos  tree y KNN

# Encontrar la intersección entre Árbol de decisión y KNN
intersection_tree_knn = list(set(tree_positivos) & set(KNN_positivos))

print("Datos positivos compartidos entre Árbol de decisión y KNN:", len(intersection_tree_knn))

Datos positivos compartidos entre Árbol de decisión y KNN: 955